// Here it shall be
node('maven') {

   def mvnCmd = "mvn -s ./nexus-openshift-settings.xml"

  stage('Checkout Source') {
    git 'https://github.com/hsavolai/ose-wall-service.git'
  }

  stage('Unit Tests') {
    sh "${mvnCmd} -P test clean test"
  }
  
  stage('Build package') {
    sh "${mvnCmd} -P prod clean package -DskipTests"
  }
  
  stage('Code Analysis') {
      sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube:9000/ -Dsonar.projectName=${JOB_BASE_NAME}"
  }

}

//node('nodejs') {
//  sh "ls" 
//}
